apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: expenses-split
  namespace: default
spec:
  service: expenses
  backends:
  - service: expenses-active
    weight: 500
  - service: expenses-preview
    weight: 500