apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: notifier-split
  namespace: default
spec:
  service: notifier
  backends:
  - service: notifier-active
    weight: 500
  - service: notifier-preview
    weight: 500