apiVersion: v1
kind: Secret
metadata:
  name: helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: 'https://raw.githubusercontent.com/hasAnybodySeenHarry/debt-tracker-services/production/'
  username: hasAnybodySeenHarry