apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifier
  name: notifier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  strategy: {}
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - image: xidepid640/notifier:v1.0.0
        name: app-container
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        livenessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        startupProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        env:
        - name: GRPC_ADDR
          value: ""
        - name: PORT
          value: "8080"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: host
        - name: MONGO_PORT
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: port
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: database
        - name: PUB_HOST
          valueFrom:
            secretKeyRef:
              name: pubsub-secret
              key: host
        - name: PUB_PORT
          valueFrom:
            secretKeyRef:
              name: pubsub-secret
              key: port
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: addr
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifier
  name: notifier-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: notifier
  type: ClusterIP