apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app.fullname" . }} 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://raw.githubusercontent.com/hasAnybodySeenHarry/services/main/production/"
    chart: {{ include "app.fullname" . }}
    targetRevision: "*"
    helm:
      valueFiles:
        - values.yaml
      # releaseName: prod-release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
