apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ include "app.fullname" . }}-app-policy
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: {{ include "app.fullname" . }}-app-route
  requiredAuthenticationRefs:
  - name: {{ include "app.fullname" . }}-app-authn
    kind: MeshTLSAuthentication
    group: policy.linkerd.io
