apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port | default "http" }}
    protocol: TCP
    targetPort: {{ .Values.service.port | default "http" }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  type: ClusterIP