apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: expenses
  name: expenses-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses
  strategy: {}
  template:
    metadata:
      labels:
        app: expenses
    spec:
      containers:
      - image: xidepid640/expenses:v1.0.0
        name: app-container
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50051
          name: grpc
        readinessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        livenessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        startupProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        env:
        - name: GRPC_PORT
          value: "50051"
        - name: PORT
          value: "8080"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: name
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: port
        - name: MAX_OPEN_CONN
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: maxOpenConn
        - name: MAX_IDLE_CONN
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: maxIdleConn
        - name: AMQP_USERNAME
          valueFrom:
            secretKeyRef:
              name: amqp-secret
              key: username
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: amqp-secret
              key: password
        - name: AMQP_HOST
          valueFrom:
            secretKeyRef:
              name: amqp-secret
              key: host
        - name: AMQP_PORT
          valueFrom:
            secretKeyRef:
              name: amqp-secret
              key: port
        - name: PUB_HOST
          valueFrom:
            secretKeyRef:
              name: pubsub-secret
              key: host
        - name: PUB_PORT
          valueFrom:
            secretKeyRef:
              name: pubsub-secret
              key: port
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: expenses
  name: expenses-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: expenses
  type: ClusterIP