apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: throttler
  name: throttler-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: throttler
  strategy: {}
  template:
    metadata:
      labels:
        app: throttler
    spec:
      containers:
      - image: xidepid640/throttler:v1.0.0
        name: app-container
        ports:
        - containerPort: 8080
          name: http
        resources: {}
        readinessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        livenessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        startupProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
        env:
        - name: GRPC_ADDR
          value: "expenses-app"
        - name: PORT
          value: "8080"
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: addr
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: throttler
  name: throttler-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: throttler
  type: ClusterIP