apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-node
  labels:
    app: zookeeper
spec:
  containers:
  - name: zookeeper
    image: bitnami/zookeeper:latest
    env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
    ports:
    - containerPort: 2181
    volumeMounts:
    - name: kafka-data
      mountPath: /bitnami/kafka
  volumes:
  - name: kafka-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-node
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-node
  labels:
    app: kafka
spec:
  containers:
  - name: kafka
    image: bitnami/kafka:3.3
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper-node:2181
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    - name: KAFKA_LISTENERS
      value: INSIDE://0.0.0.0:9092,OUTSIDE://localhost:9093
    - name: KAFKA_ADVERTISED_LISTENERS
      value: INSIDE://kafka-node:9092,OUTSIDE://localhost:9093
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: INSIDE
    - name: KAFKA_HOST
      valueFrom:
        secretKeyRef:
          name: pubsub-secrets
          key: host
    - name: KAFKA_PORT
      valueFrom:
        secretKeyRef:
          name: pubsub-secrets
          key: port
    ports:
    - containerPort: 9092
    - containerPort: 9093
    volumeMounts:
    - name: kafka-data
      mountPath: /bitnami/kafka
  volumes:
  - name: kafka-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-node
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  - port: 9093
    targetPort: 9093
    name: kafka-management
  selector:
    app: kafka
