{{- $original := . }}
{{- range $suffix := list "active" "preview" }}
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: {{ include "app.fullname" $original }}-{{ $suffix }}.default.svc.cluster.local
  namespace: default
spec:
  routes:
    - name: {{ include "app.fullname" $original }}-{{ $suffix }}-route
      condition:
        pathRegex: "^/v[0-9]+$" # "/.*"
        method: "GET"
      isRetryable: true
  retryBudget:
    minRetriesPerSecond: 10
    retryRatio: 0.2
    ttl: "10s"
---
{{- end }}