apiVersion: v2
name: throttler
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/hasAnybodySeenHarry/cluster
sources:
- https://github.com/hasAnybodySeenHarry/cluster