replicaCount: 1

image:
  repository: xidepid640/throttler
  pullPolicy: IfNotPresent
  tag: v2.0.0

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

livenessProbe:
  path: /v1/healthcheck
  port: 8080

readinessProbe:
  path: /v1/healthcheck
  port: 8080

startupProbe:
  path: /v1/healthcheck
  port: 8080

env:
- name: GRPC_ADDR
  value: "expenses"
- name: PORT
  value: "8080"
- name: REDIS_ADDR
  valueFrom:
    secretKeyRef:
      name: redis-secret
      key: addr
- name: REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: redis-secret
      key: password